### ISSUE TITLE
can't download the model

### ISSUE THREAD

**Issue by huukim136** [Honlan/BeautyGAN#2]
This project seems to be very helpful to me. I have cloned the project but cannot download the model from baidu because it requires a Chinese account to do this task.
Can you please upload the model to Google Drive. I would very appreciate it!

**Comment by Honlan** [comment]
I have uploaded the model files to Google Drive and added the link to README

**Comment by Cortlandd** [comment]
This is probably what you want. Author of this repos implementation may be a bit more accurate. https://github.com/baldFemale/beautyGAN-tf-Implement
